### ISSUE TITLE
Implement course type picker fragment

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-android#32]
Design course type picker fragment.

Please define related colors and text & button styles in the corresponding values files.

![image](https://user-images.githubusercontent.com/1358055/113606939-50f9d600-9651-11eb-9e08-1e13269c5691.png)

Please use material design guidelines for android. The figma design is a bit ios oriented, it needs a bit of adapting for android :) For example, the title should be placed in the action bar with a back button instead of the X.

[Link to API in swagger](https://api.deurgenta.hostmysite.ro/swagger/index.html)

[Link to design in Figma](https://www.figma.com/file/d6n3MPVRWbL5jP2NmvW96b/De_Urgenta?node-id=1466%3A530)

**Comment by lukstbit** [comment]
Do the type and/or the city will come from the backend?

**Comment by lukstbit** [comment]
Will the types/cities be retrieved from the backend?

**Comment by aniri** [comment]
> Will the types/cities be retrieved from the backend?

@lukstbit yep, there will be endpoints for retrieving them. thanks for pointing this out ;)

**Comment by lukstbit** [comment]
I've created the UI related to courses but it would be helpful to have the endpoint available to bind it together!

**Comment by aniri** [comment]
added backend issue for the endpoints: https://github.com/code4romania/de-urgenta-backend/issues/50

**Comment by aniri** [comment]
@lukstbit if you think it might be easier, we could merge the UI part now with some dummy data and handle the backend integration later :)

**Comment by lukstbit** [comment]
I'll make a PR tomorrow to have time for one more look through the code.

**Comment by lukstbit** [comment]
Done. 
On a side note I think the courses UI could be improved:

- the current design shows a info fragment with information to the user which is really valuable the first or second time the user enters the courses flow, after this the info is useless and becomes just another screen in the courses flow.
- the current design separates the filtering and listing the courses which again is not that great because the user has to see two loading screens to get to the data
- the UI is deep, starting from the info fragment the user has 3 levels to navigate to see the course details and 3 levels back to see the navigation drawer again

I was thinking of improving the design by having only two fragments, courses and details:
- in courses we could show a panel with the info in the fragment when the user first visits the courses flow and also a menu item called info(so the user will always have access to that info)
- in courses we could show the action bar + a tab bar(or bottom bar) with two tabs: a tab with the list of courses and a tab with a calendar with the courses
- in courses the filtering will be done through an always visible menu item
- in courses there will be only one loading screen for everything(the requests for filtering options and the actual course could be done simultaneously)
- the UI will be shallow, just 1 extra level from courses, one back/up action from the details screen will make the navigation drawer available to the user.

**Comment by aniri** [comment]
> On a side note I think the courses UI could be improved:
> 
> * the current design shows a info fragment with information to the user which is really valuable the first or second time the user enters the courses flow, after this the info is useless and becomes just another screen in the courses flow.
> * the current design separates the filtering and listing the courses which again is not that great because the user has to see two loading screens to get to the data
> * the UI is deep, starting from the info fragment the user has 3 levels to navigate to see the course details and 3 levels back to see the navigation drawer again
> 
> I was thinking of improving the design by having only two fragments, courses and details:
> 
> * in courses we could show a panel with the info in the fragment when the user first visits the courses flow and also a menu item called info(so the user will always have access to that info)
> * in courses we could show the action bar + a tab bar(or bottom bar) with two tabs: a tab with the list of courses and a tab with a calendar with the courses
> * in courses the filtering will be done through an always visible menu item
> * in courses there will be only one loading screen for everything(the requests for filtering options and the actual course could be done simultaneously)
> * the UI will be shallow, just 1 extra level from courses, one back/up action from the details screen will make the navigation drawer available to the user.

@lukstbit wow 👀 these are really good ideas! We'll discuss them also with the ux/ui team and will most likely make new issues with these improvements 🚀 For the moment, we can merge this PR while we wait for the backend part and some better UI :D
